services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:7.2.3
    environment:
      REDIS_PASSWORD: kjungle3!
      TZ: Asia/Seoul
    command:  ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      # - /etc/localtime:/etc/localtime:ro

volumes:
  mysql_data:
  redis_data:
